<div class="ocaml_toplevel_module"><div class="info">This module is the deferred analog of <code class="code">Core.Or_error</code>. It is exposed in std.ml as
    <code class="code">Deferred.Or_error</code>.<p>    The mental model for a function returning an <code class="code">'a Deferred.Or_error.t</code> is that the
    function never raises.  All error cases are caught and expressed as an <code class="code">Error _</code>
    result.  This module preserves that property.</p><p>    Unfortunately, there is no way to enforce this property using the type system, so it
    is more like a convention, or idiom.  A function whose type ends with <code class="code">... -&gt; 'a
    Deferred.Or_error.t</code> and still raises should be considered broken, and be fixed.  With
    that property in mind, <code class="code">Deferred.Or_error.List.iter</code>, for example, does not wrap the
    execution of the given iter function <code class="code">f</code> inside a monitor.  If one of these
    application raises, the whole function <code class="code">Deferred.Or_error.List.iter</code> will raise as a
    way to try to alert the developer that one the function is broken and needs attention
    and fixing, rather than silently catching the error and converting it to
    <code class="code">Or_error.Error</code>.</p><p>    This behavior is consistent with <code class="code">Core.Or_error</code>'s treatment of user-supplied
    functions.</p><p>    If you have to deal with a function that does not respect this idiom, you can use
    <code class="code">Deferred.Or_error.try_with_join</code> to wrap its execution and enforce this property.</p></div>
<pre><span class="TYPEt"><span class="keyword">type</span> <code class="type">'a </code>t</span> = <code class="type">'a <a href="?package=core&amp;module=Std.Or_error&amp;type=t">Core.Std.Or_error.t</a> <a href="?package=async_core&amp;module=Deferred&amp;type=t">Deferred.t</a></code></pre>
<div class="ocaml_include ident" path="?package=core&amp;module=Std.Monad.S" items="[&quot;Monad_infix&quot;]"><pre><span class="keyword">include</span> <code class="type"><code class="code"><a href="?package=core&amp;module=Std.Monad.S">Core.Std.Monad.S</a></code> with type t := 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre><div class="info"><div class="info"><code class="code">return x = Deferred.return (Ok x)</code> *</div></div></div>
<pre><span class="VALfail"><span class="keyword">val</span> fail</span> : <code class="type"><a href="?package=core&amp;module=Std.Error&amp;type=t">Core.Std.Error.t</a> -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre><div class="info"><div class="info"><code class="code">fail error = Deferred.return (Error error)</code> *</div></div>
<pre><span class="VALok_exn"><span class="keyword">val</span> ok_exn</span> : <code class="type">'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a> -&gt; 'a <a href="?package=async_core&amp;module=Deferred&amp;type=t">Deferred.t</a></code></pre><div class="info"><div class="info">These functions are direct analogs of the corresponding <code class="code">Core.Or_error</code> functions.</div></div>
<pre><span class="VALof_exn"><span class="keyword">val</span> of_exn</span> : <code class="type">exn -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALof_exn_result"><span class="keyword">val</span> of_exn_result</span> : <code class="type">('a, exn) <a href="?package=core&amp;module=Std.Result&amp;type=t">Core.Std.Result.t</a> <a href="?package=async_core&amp;module=Deferred&amp;type=t">Deferred.t</a> -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALerror"><span class="keyword">val</span> error</span> : <code class="type">string -&gt; 'a -&gt; ('a -&gt; <a href="?package=core&amp;module=Std.Sexp&amp;type=t">Core.Std.Sexp.t</a>) -&gt; 'b <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALerror_string"><span class="keyword">val</span> error_string</span> : <code class="type">string -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALunimplemented"><span class="keyword">val</span> unimplemented</span> : <code class="type">string -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALcombine_errors"><span class="keyword">val</span> combine_errors</span> : <code class="type">'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a> list -&gt; 'a list <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALcombine_errors_unit"><span class="keyword">val</span> combine_errors_unit</span> : <code class="type">unit <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a> list -&gt; unit <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<pre><span class="VALok_unit"><span class="keyword">val</span> ok_unit</span> : <code class="type">unit <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre><div class="info"><div class="info"><code class="code">ok_unit = return ()</code></div></div>
<pre><span class="VALtry_with"><span class="keyword">val</span> try_with</span> : <code class="type">?extract_exn:bool -&gt; ?name:string -&gt; (unit -&gt; 'a <a href="?package=async_core&amp;module=Deferred&amp;type=t">Deferred.t</a>) -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre><div class="info"><div class="info"><code class="code">try_with f</code> catches exceptions thrown by <code class="code">f</code> and returns them in the Result.t as an
    Error.t.  <code class="code">try_with_join</code> is like <code class="code">try_with</code>, except that <code class="code">f</code> can throw exceptions or
    return an <code class="code">Error</code> directly, without ending up with a nested error; it is equivalent to
    <code class="code">try_with f &gt;&gt;| Result.join</code>.<p>    The option <code class="code">extract_exn</code> is passed along to <code class="code">Monitor.try_with ?extract_exn</code> and
    specifies whether or not the monitor exn wrapper should be skipped (<code class="code">extract_exn:true</code>
    or kept (<code class="code">extract_exn:false</code>).</p></div></div>
<pre><span class="VALtry_with_join"><span class="keyword">val</span> try_with_join</span> : <code class="type">?extract_exn:bool -&gt; ?name:string -&gt; (unit -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a>) -&gt; 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a></code></pre>
<div class="ocaml_module ident" name="List" path="?package=async_core&amp;module=Deferred_intf.Monad_sequence"><pre><span class="keyword">module</span> <a href="?package=async_core&amp;module=Async_or_error.List">List</a> : <code class="type"><code class="code"><a href="?package=async_core&amp;module=Deferred_intf.Monad_sequence">Deferred_intf.Monad_sequence</a></code> with type monad := 'a <a href="?package=async_core&amp;module=Async_or_error&amp;type=t">t</a> with type t := 'a list</code></pre></div>
</div>